hwgraph: Prevent crash if thermal sensors are not yet populated
When the BMC got reset recently, the thermals are set to None generating
an Exception like the following:

  File "/root/hwbench/hwbench/environment/vendors/dell/dell.py", line 18, in read_thermals
    if t["ReadingCelsius"] <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

This commit test first ReadingCelsius is set before comparing to an int.

Signed-off-by: Erwan Velu <e.velu@criteo.com>